
project_id = "msgqsgftjwpbnqenhfmc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://tortshark.lovable.app"

[analytics]
enabled = true

[functions.lead-prosper-campaigns]
verify_jwt = true

[functions.lead-prosper-auth]
verify_jwt = true

[functions.lead-prosper-sync]
verify_jwt = true

[functions.lead-prosper-fetch-today]
verify_jwt = true

[functions.lead-prosper-verify]
verify_jwt = true

[functions.lead-prosper-webhook]
verify_jwt = false
