
project_id = "msgqsgftjwpbnqenhfmc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions.google-oauth]
verify_jwt = true

[functions.google-ads-data]
verify_jwt = true
