
project_id = "msgqsgftjwpbnqenhfmc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[vector]
enabled = true

[edge_functions]
[edge_functions.google-ads]
verify_jwt = true

[edge_functions.google-ads-mapping]
verify_jwt = true

[edge_functions.google-oauth]
verify_jwt = true

[edge_functions.google-ads-data]
verify_jwt = true

[edge_functions.google-ads-manager]
verify_jwt = true

[edge_functions.upload-logo]
verify_jwt = true

[edge_functions.extract-tort-coverage]
verify_jwt = true

[edge_functions.lead-prosper-auth]
verify_jwt = true

[edge_functions.lead-prosper-campaigns]
verify_jwt = true

[edge_functions.lead-prosper-sync]
verify_jwt = true

[edge_functions.lead-prosper-webhook]
verify_jwt = false

